name: CitizensTradeGUI
version: 1.0
main: com.example.citizenstrade.CitizensTradeGUI
api-version: 1.20
authors: [beiuu]
depend: [Vault, Citizens]
commands:
  ctg:
    description: Edit GUI trading for Citizens NPCs
    usage: /ctg edit
